name: Deploy Local Dev Server

on:
  push:
    branches: [ feature/frontend ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Kill existing dev server
      run: |
        $processes = Get-Process -Name "node" -ErrorAction SilentlyContinue | Where-Object { $_.MainWindowTitle -like "*vite*" -or $_.CommandLine -like "*vite*" }
        if ($processes) {
          $processes | Stop-Process -Force
        }
        Start-Sleep -Seconds 2
    
    - name: Install dependencies
      run: npm install
    
    - name: Start dev server
      run: |
        Start-Process -FilePath "npm" -ArgumentList "run", "dev" -WindowStyle Hidden
        Start-Sleep -Seconds 5