name: Deploy Backend to EC2

on:
  push:
    branches: [ feature/backend ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy backend with rsync
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr --delete --exclude='.git' --exclude='node_modules'
        path: ./
        remote_path: /home/ec2-user/nutrition-backend/
        remote_host: 44.214.236.166
        remote_user: ec2-user
        remote_key: ${{ secrets.EC2_SSH_KEY }}
    
    - name: Restart Node.js backend server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 44.214.236.166
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        timeout: 60s
        command_timeout: 30s
        script: |
          pkill -f 'node.*app.js' || true
          sleep 2
          cd /home/ec2-user/nutrition-backend/backend || exit 1
          npm install --production
          nohup npm start > ../backend.log 2>&1 &
          sleep 5
          ps aux | grep 'node.*app.js' | grep -v grep
          echo "Backend deployment completed"