name: Deploy Backend to EC2

on:
  push:
    branches: [ feature/backend ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy backend with rsync
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr --delete --exclude='.git' --exclude='node_modules'
        path: ./
        remote_path: /home/ec2-user/nutrition-backend/
        remote_host: 44.214.236.166
        remote_user: ec2-user
        remote_key: ${{ secrets.EC2_SSH_KEY }}
    
    - name: Start backend
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: 44.214.236.166
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        timeout: 30s
        script: |
          #!/bin/bash
          set -e
          pkill node || echo "No node process to kill"
          cd /home/ec2-user/nutrition-backend/backend
          npm install --silent
          nohup node src/app.js > backend.log 2>&1 < /dev/null &
          disown
          echo "Backend deployment completed"