name: Deploy to EC2

on:
  push:
    branches: [ feature/frontend ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Deploy with rsync
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr --delete
        path: dist/
        remote_path: /home/ec2-user/nutrition-app/dist/
        remote_host: 44.214.236.166
        remote_user: ec2-user
        remote_key: ${{ secrets.EC2_SSH_KEY }}
    
    - name: Restart server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: 44.214.236.166
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        timeout: 10s
        script: |
          pkill -f 'serve.*3000' || true
          cd ~/nutrition-app && nohup serve -s dist -l 3000 &
          echo "Server restarted"