name: Deploy to EC2

on:
  push:
    branches: [ feature/frontend ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Create deployment package
      run: |
        cd dist
        tar -czf ../deploy.tar.gz .
        cd ..
    
    - name: Deploy to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: 44.214.236.166
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "deploy.tar.gz"
        target: "~/"
    
    - name: Extract and restart
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: 44.214.236.166
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        timeout: 60s
        script_stop: true
        script: |
          pkill -f 'serve.*3000' || true
          cd ~/nutrition-app
          rm -rf dist_old && mv dist dist_old 2>/dev/null || true
          mkdir -p dist && cd dist
          tar -xzf ~/deploy.tar.gz
          cd ~/nutrition-app
          export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
          serve -s dist -l 3000 > /dev/null 2>&1 &
          rm ~/deploy.tar.gz
          echo "Deployment completed successfully!"