name: Deploy Backend to EC2

on:
  push:
    branches: [ feature/backend ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Deploy backend with rsync
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr --delete --exclude='.git' --exclude='__pycache__' --exclude='*.pyc'
        path: ./
        remote_path: /home/ec2-user/nutrition-backend/
        remote_host: 44.214.236.166
        remote_user: ec2-user
        remote_key: ${{ secrets.EC2_SSH_KEY }}
    
    - name: Restart backend server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: 44.214.236.166
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        timeout: 30s
        script: |
          cd ~/nutrition-backend
          pkill -f 'python.*app.py' || true
          sleep 2
          source venv/bin/activate || python -m venv venv && source venv/bin/activate
          pip install -r requirements.txt
          nohup python app.py > backend.log 2>&1 &
          sleep 3
          ps aux | grep 'python.*app.py' | grep -v grep || echo "Backend start failed"
          echo "Backend deployment completed!"